### ISSUE TITLE
Integrate Storybook and setup pattern/component library

### ISSUE THREAD

**Issue by LionOnTheWeb** [LionOnTheWeb/lionontheweb-web#52]

**Comment by LionOnTheWeb** [comment]
I wanted to build an automated workflow that would publish my Storybook changes to Chromatic, the official storybook hosting platform, whenever I made a push to a release branch for a final design review before any new UI features get deployed to production. 

To set this up, I first followed the steps outlined in [Chromatic's Github Actions doc](https://www.chromatic.com/docs/github-actions) to test this workflow: 

```yaml
# .github/workflows/chromatic.yml

# Workflow name
name: 'Chromatic'

# Event for the workflow
on: push

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        # 👇 Install dependencies with the same package manager used in the project (replace it as needed), e.g. yarn, npm, pnpm
        run: yarn
        # 👇 Adds Chromatic as a step in the workflow
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
```

# Errors

## Github Actions Checkout@v2 vs Checkout@v3
The first error I encountered was actually an error with the Github action I was using to checkout my branch:

```bash
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```

This was because of a recent decision to standardize newer versions of Node to provide numerous benefits to the security of GH Actions. After looking up [solutions](https://github.com/actions/checkout/issues/1047), the easiest was to upgrade the checkout actions step to use version 3 of the action, which uses `Node v^16.x.x`. 
I simply added `uses: actions/checkout@v3` to the `.yml` workflow to address the issue. 

## Chromatic Project Token
The second issue I encountered was that the workflow job to publish to Chromatic wasn't picking up the project token needed to run the deploy/publish Chromatic job. This is a private token to your project and should not be accessible from any source code. Therefore, I needed to fetch this project token in [GH secrets](https://docs.github.com/en/actions/security-guides/encrypted-secrets).

I had added this token to my secrets envs: 


![Image](https://github.com/LionOnTheWeb/lionontheweb-web/assets/38708680/5ece1a9a-b71c-4de4-92d7-1040e7b73683)

But it _still_ wasn't being recognized. I encountered errors like the following:

```bash
Run chromaui/action@v1
  with:
    onlyChanged: true
    traceChanged: true
  env:
    projectToken: 

Chromatic CLI v6.17.[4](https://github.com/LionOnTheWeb/lionontheweb-web/actions/runs/5021181406/jobs/9003310988#step:4:4)
https://www.chromatic.com/docs/cli

✖ Missing project token
```

I realized after a few hours of research into the issue, that I was added env secrets, but not *_global_* repo secrets. 

![Image](https://github.com/LionOnTheWeb/lionontheweb-web/assets/38708680/fefb7a52-a660-4952-96d3-ab09ee320ec8)

This then fixed the issue. Env secrets would be useful, but since I _only_ plan to publish to Chromatic when a feature PR is merged into the appropriate `release/` branch, I don't need to necessarily worry about the environments at this time and I only have one token and one Chromatic Storybook env. 

## Publishing to Chromatic
We can publish to Chromatic using their deployment action-- `uses: chromaui/action@v1`. Following the [Chromatic's Github Actions doc](https://www.chromatic.com/docs/github-actions), I created the following step to publish:

```yaml
- name: Publish to Chromatic
        id: chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: storybook:build
          onlyChanged: true
          traceChanged: true
```

**Note: It is important to use _spaces_ instead of _tabs_** for these yaml config files.

Currently, I get the following build error in my workflow:
```bash
Building your Storybook
    → Running command: npm run --silent storybook:build -- --output-dir /tmp/chromatic--1743-tHqp95o93qUF --webpack-stats-json /tmp/chromatic--1743-tHqp95o93qUF
    → [*                   ]
The CLI tried to run your storybook:build script, but the command failed. This indicates a problem with your Storybook. Here's what to do:

- Check the Storybook build log printed below.
- Run npm run storybook:build or yarn storybook:build yourself and make sure it outputs a valid Storybook by opening the generated index.html in your browser.
- Review the build-storybook CLI options at https://storybook.js.org/docs/configurations/cli-options/#for-build-storybook

Command failed with exit code 1: npm run --silent storybook:build -- --output-dir /tmp/chromatic--1743-tHqp95o93qUF --webpack-stats-json /tmp/chromatic--1743-tHqp95o93qUF
```

According to this error, the Chromatic CLI isn't running my custom Storybook build script available in my `package.json`. Here, I am using a different build script key than Chromatic's default, which is `build-storybook`. 

To fix this, I either need to reset the defaults of the publish job, or troubleshoot how to use the build script I set, and configure the publish job to target my designated output SB folder, which I've set to be built and output to a `pattern-library` folder with this build script: 

`"storybook:build": "storybook build -c .storybook -o pattern-library"`
